config/routes.rb
Rails.application.routes.draw do
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  root 'welcome#index'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users, except: [:index] do
    member do
      get :following, :followers, :owned, :saved, :funded
    end
  end
  resources :projects do
    member do
      get :savers
      post :save
      delete :forget
    end
  end
  get '/search', to: 'projects#search'
  get '/claim', to: 'projects#claim'
  resources :donations, only: %i[new create]
  resources :relationships, only: %i[create destroy]
  resources :project_relationships, only: %i[create destroy]
  resources :comments, only: %i[index new create show]

  namespace :api do
    namespace :v1 do
      resources :projects, only: [:index, :create, :show] do
        member do
          post :save
          delete :forget
        end
        resources :comments, only: [:index, :new, :create, :show]
      end
      resources :users, only: [:show, :create] do
        member do
          patch :update
        end
      end
      post 'users/:id/follow', to: 'users#follow'
      post 'users/:id/unfollow', to: 'users#unfollow'
      get 'users/:id/followers', to: 'users#followers'
      get 'users/:id/following', to: 'users#following'
      resources :donations, only: [:create]
      resources :comments, only: [:create, :show]
      post '/telegram', to: 'telegram#handle'
      get '/telegram', to: 'telegram#activate'
    end
  end

  get '*path' => redirect('/')

end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true, allow_blank: false
  belongs_to :user
  belongs_to :project
end

app/controllers/api/v1/comments_controller.rb
# frozen_string_literal: true

module Api::V1
  class CommentsController < ApiController
    before_action :authenticate

    def create
      @comment = @current_user.comments.build(comment_params)
      return if @comment.save
      render json: { errors: @comment.errors }, status: :unprocessable_entity
    end

    def index
      @comments = Project.find(comment_params[:project_id].to_i).comments
      render json: @comments
    end

    def show
      @comment = Comment.find(comment_params[:id].to_i)
      render json: @comment
    end

    private

    def comment_params
      params.permit(:project_id, :content, :id)
    end
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  include Secured
  before_action :set_comment, only: %i[show edit update destroy]
  before_action :is_logged_in?, only: %i[new create edit update destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show; end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit; end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @project = @comment.project
    respond_to do |format|
      if @comment.save
        text = "The project '#{@project.brief}' has a new comment on it: \n"
        text += "#{@comment.user.fullname}: '#{@comment.content.strip()}'\n"
        text += "Visit it here to know more: #{project_url(@project)}"
        registry = []
        if !@project.user.chat_id.nil?
          BOT.send_message(@project.user.chat_id, text)
        end
        User.donors_of(@project).with_telegram.each do |user|
          BOT.send_message(user.chat_id, text)
          registry << user.id
        end
        @project.savers.with_telegram.each do |user|
          BOT.send_message(user.chat_id, text) unless registry.include?(user.id)
        end
        format.html { redirect_to project_path(@comment.project, anchor: 'comments-section'), notice: 'Comment was successfully created.' }
        format.js { render 'new_comment.js.erb' }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:content, :project_id).merge(user_id: current_user.id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment_preview.html.erb
<li>
	<div class="comment-main">
		 <a href="<%= user_path(comment.user)%>"><%= image_tag comment.user.avatar.url(:comment), class: "img-circle"%></a>
		<div class="comment-square">
			<div class="comment-content">
				<span class="square-arrow"></span>
				<p class="comment-author">
					<%= link_to comment.user.fullname, comment.user%><span id="SPAN_21"></span>
				</p>
				<p class="comment-date">
					<%= distance_of_time_in_words(Time.now, comment.created_at)%> ago
				</p>
				<div class="spacer"></div>
				<p class=content-body>
						<span><%=comment.content%></span>
				</p>
			</div>
		</div>
	</div>
</li>

app/views/comments/_form.html.erb
<%= form_for(comment) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content, required: true %>
  </div>

  <div class="field">
    <%= f.hidden_field :project_id, :value => params[:project_id]%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/comments.js.erb
 $(".comment-container").html("<div class='comment-item'><%= escape_javascript(render partial: 'comment_preview', locals: { {comment: @comment, project: @project} } ) %></div>"); 

app/views/comments/edit.html.erb
<h1 class="page-title">Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1 class="page-title">Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Project</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user %></td>
        <td><%= comment.project %></td>
        <td><%= comment.content %></td>
        <td><%= link_to 'Show', comment %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1 class="page-title">New Comment</h1>
<%= render 'form', {comment: @comment, project_id: @project_id}%>
<%= link_to 'Back', comments_path %>

app/views/comments/new_comment.js.erb
$(".comment-container").append("<div class='comment-item'><%= escape_javascript(render 'comment_preview', {comment: @comment, project: @project })%></div>");
 $('.comment-container')[0].scrollIntoView(false);

app/views/comments/show.html.erb
<p>
  <strong>User:</strong>
  <%= @comment.user.fullname %>
</p>

<p>
  <strong>Project:</strong>
  <%= @comment.project.brief %>
</p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>