config/routes.rb
Rails.application.routes.draw do
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  root 'welcome#index'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users, except: [:index] do
    member do
      get :following, :followers, :owned, :saved, :funded
    end
  end
  resources :projects do
    member do
      get :savers
      post :save
      delete :forget
    end
  end
  get '/search', to: 'projects#search'
  get '/claim', to: 'projects#claim'
  resources :donations, only: %i[new create]
  resources :relationships, only: %i[create destroy]
  resources :project_relationships, only: %i[create destroy]
  resources :comments, only: %i[index new create show]

  namespace :api do
    namespace :v1 do
      resources :projects, only: [:index, :create, :show] do
        member do
          post :save
          delete :forget
        end
        resources :comments, only: [:index, :new, :create, :show]
      end
      resources :users, only: [:show, :create] do
        member do
          patch :update
        end
      end
      post 'users/:id/follow', to: 'users#follow'
      post 'users/:id/unfollow', to: 'users#unfollow'
      get 'users/:id/followers', to: 'users#followers'
      get 'users/:id/following', to: 'users#following'
      resources :donations, only: [:create]
      resources :comments, only: [:create, :show]
      post '/telegram', to: 'telegram#handle'
      get '/telegram', to: 'telegram#activate'
    end
  end

  get '*path' => redirect('/')

end

app/views/shared/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "follow-btn btn-primary" %>
<% end %>

app/views/shared/_follow_form.html.erb
<% if current_user.following?(@user) %>
    <%= render 'shared/unfollow' %>
  <% else %>
    <%= render 'shared/follow' %>
  <% end %>

app/views/shared/_footer.html.erb
<p>IIC2513 - Tecnologías y Aplicaciones Web | DreamFunder &copy; | Created by Juan Pablo Jofré &amp; Vicente Fuenzalida</p>
<p><%= mail_to "vjfuenzalida@uc.cl", "Contact Us" %> | <%= link_to "GitHub", "https://github.com/IIC2513-2017-1/grupo-12"%></p>

app/views/shared/_navbar.html.erb
<nav class="navbar-container">
  <ul class="navbar navbar-left">
    <li id="brand" class="<%= active_class('welcome', 'index') %>"><%= link_to "DreamFunder", root_path%></li>
    <!--<li class="<%#= active_class('users', 'index') %>"><%#= link_to "Users", users_path%></li>-->
    <li class="<%= active_class('projects', 'index') %>"><%= link_to "Explore", projects_path%></li>
    <% if logged_in? %>
      <%ide = current_user.id%>
      <li class="dropdown <%= active_class('users', 'owned', ide)+active_class('users', 'funded', ide)+active_class('users', 'saved', ide) %>">
        <span>Projects</span>
        <div class="dropdown-content">
          <%= link_to "My Projects", owned_user_path(current_user)%>
          <%= link_to "Financed", funded_user_path(current_user)%>
          <%= link_to "Bookmarks", saved_user_path(current_user)%>
        </div>
      </li>
      <!--<li class="<%#= active_class('users', 'funded', ide) %>"><%#= link_to "Financed", funded_user_path(current_user)%></li>-->
      <!--<li class="<%#= active_class('users', 'saved', ide) %>"><%#= link_to "Bookmarks", saved_user_path(current_user)%></li>-->
    <%end %>
      <li class="search-tab">
        <%= form_tag(search_path, method: 'get') do %>
          <%= search_field_tag 'search', nil, class: 'form-control search-box', placeholder: 'Search Projects'  %>
        <% end %>
      </li>
  </ul>
  <ul class="navbar navbar-right">
    <% if logged_in? %>
      <%ide = current_user.id%>
      <li class="<%= active_class('projects', 'new') %>"><%= link_to "Create Project", new_project_path%></li>
      <li class="<%='dropdown nav-right-img ' + active_class('users', 'show', ide)%>">
        <a href="<%= user_path(current_user) %>">
          <%= image_tag current_user.avatar.url(:thumb), class: "img-circle", alt: ""%>
          <span class="navbar-user"><%= current_user.fullname %></span>
        </a>
        <div class = "dropdown-content">
          <%= link_to 'Settings', edit_user_path(current_user) %>
          <%= link_to "Logout", logout_path, {method: :delete}%>
        </div>
      </li>
    <% else %>
      <li class="<%='nav-right ' + active_class('sessions', 'new')%>"><%= link_to "Login", login_path%></li>
      <li class="<%='nav-right ' + active_class('users', 'new')%>"><%= link_to "Signup", signup_path%></li>
    <% end %>
  </ul>
</nav>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<ul>
  <li class="user-following">
    <a href="<%= following_user_path(@user) %>">
      <strong><%= @user.following.count %></strong>
      following
    </a>
  </li>
  <li class="user-followers">
    <a href="<%= followers_user_path(@user) %>">
      <strong><%= @user.followers.count %></strong>
      followers
    </a>
  </li>
</ul>

app/views/shared/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "follow-btn" %>
<% end %>

app/views/shared/_user_stats.html.erb
<ul class="follow-stats">
  <li class="follow-stats">
    <a href="<%= following_user_path(user) %>">
      <strong><%= user.following.count %></strong>
      following
    </a>
  </li>
   |
  <li class="follow-stats">
    <a href="<%= followers_user_path(user) %>">
      <strong><%= user.followers.count %></strong>
      followers
    </a>
  </li>
</ul>