config/routes.rb
Rails.application.routes.draw do
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  root 'welcome#index'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users, except: [:index] do
    member do
      get :following, :followers, :owned, :saved, :funded
    end
  end
  resources :projects do
    member do
      get :savers
      post :save
      delete :forget
    end
  end
  get '/search', to: 'projects#search'
  get '/claim', to: 'projects#claim'
  resources :donations, only: %i[new create]
  resources :relationships, only: %i[create destroy]
  resources :project_relationships, only: %i[create destroy]
  resources :comments, only: %i[index new create show]

  namespace :api do
    namespace :v1 do
      resources :projects, only: [:index, :create, :show] do
        member do
          post :save
          delete :forget
        end
        resources :comments, only: [:index, :new, :create, :show]
      end
      resources :users, only: [:show, :create] do
        member do
          patch :update
        end
      end
      post 'users/:id/follow', to: 'users#follow'
      post 'users/:id/unfollow', to: 'users#unfollow'
      get 'users/:id/followers', to: 'users#followers'
      get 'users/:id/following', to: 'users#following'
      resources :donations, only: [:create]
      resources :comments, only: [:create, :show]
      post '/telegram', to: 'telegram#handle'
      get '/telegram', to: 'telegram#activate'
    end
  end

  get '*path' => redirect('/')

end

app/models/project.rb
class Project < ApplicationRecord
  validates :brief, presence: true, allow_blank: false
  validates :description, presence: true, allow_blank: false
  validates :funding_duration, presence: true, allow_blank: false
  validates :funding_goal, presence: true, allow_blank: false
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :donations, dependent: :destroy
  has_many :pictures, dependent: :destroy
  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations
  has_many :passive_project_relationships, class_name:  'ProjectRelationship',
                                           foreign_key: 'saved_id',
                                           dependent:   :destroy
  has_many :savers, through: :passive_project_relationships, source: :saver, dependent: :destroy
  validates_associated :comments
  validates_associated :donations
  has_attached_file :picture
  self.per_page = 6
  searchkick

  scope :with_category, ->(category) { joins(:categorizations).where(categorizations: { category: category }) }

  def saver?(user)
    savers.include?(user)
  end

  def add_category(category)
    categories << category unless categories.include? category
  end

  def remove_category(category)
    categories.delete(category)
  end

  def donated
    donations.map(&:amount).inject(0) { |sum, x| sum + x }
  end

  def percentage
    (donated.to_f * 100 / funding_goal.to_f).round
  end

  def remaining
    funding_goal - donated
  end
end

app/controllers/api/v1/projects_controller.rb
# frozen_string_literal: true

module Api::V1
  class ProjectsController < ApiController
    before_action :authenticate, only: %i[create save forget]

    def index
      @projects = Project.all
    end

    def create
      # @project = Project.new(project_params)
      @project = @current_user.projects.build(project_params)
      if @project.save
        cats = params[:category_ids]&.map! { |c| c.to_i }
        unless cats.nil?
          cats.delete(0)
          categories = Category.where(id: cats)
          categories.each do |cat|
            @project.add_category(cat)
          end
        end
        render json: { status: 200, link: project_url(@project) }
      else
        render json: { errors: @project.errors }, status: :unprocessable_entity
      end
    end

    def show
      @project = Project.find(params[:id])
    end

    def save
      @project = Project.find(params[:id])
      relation = @current_user.save_project(@project)
      @followers = @project.savers.count
      return if relation
      render json: { errors: relation.errors }, status: :unprocessable_entity
    end

    def forget
      @project = Project.find(params[:id])
      forgotten = @current_user.forget_project(@project)
      @followers = @project.savers.count
      return if forgotten
      render json: { errors: forgotten.errors }, status: :unprocessable_entity
    end

    private

    def project_params
      params.require(:project).permit(:brief, :description, :funding_duration, :funding_goal, images: [], category_ids: [])
    end
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  include Secured
  before_action :set_project, only: %i[show edit update destroy save forget claim]
  before_action :project_params, only: %i[create update]
  before_action :is_logged_in?, only: %i[new create edit update destroy]

  # GET /projects
  # GET /projects.json
  def index
    extra = ''
    @category = ''
    @projects = Project.paginate(page: params[:page])
    if params['category'] && params['category'].to_i.positive?
      cat = Category.find(params['category'])
      @category = cat.name
      @projects = Project.with_category(cat).paginate(page: params[:page])
      extra = " about #{@category}".upcase
    end
    @title = "EXPLORE #{@projects.count} " + 'project'.pluralize(@projects.count).upcase + extra
    @default = if cat.nil?
                 0
               else
                 cat.id
               end
    respond_to do |format|
      format.js do
        render 'index.js.erb'
      end
      format.html { render :index }
    end
    # @projects = Project.paginate(page: params[:page])
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    if logged_in?
      @default = if current_user.saving?(@project)
                   'Unfollow'
                 else
                   'Follow'
                 end
    end
    @comments = @project.comments
    @donated = @project.donations.map(&:amount).inject(0) { |sum, x| sum + x }
    @supporters = @project.donations.pluck(:user_id).uniq.count
    @followers = @project.savers.count
    @comment = Comment.new
  end

  # GET /projects/new
  def new
    @project = Project.new
    @min_date = Date.today + 20.days
    @categories = []
  end

  # GET /projects/1/edit
  def edit
    @min_date = Date.today + 20.days
    @categories = @project.categories
  end

  # POST /projects
  # POST /projects.json
  def create
    # @category_id = project_params[:category_ids]
    project_params.delete :category_ids
    # @category = Category.find(project_params[:category_ids])
    @project = Project.new(project_params.except(:images))
    # @project.add_category(@category)
    cat_ids = project_params[:category_ids]&.map(&:to_i)
    if cat_ids.nil?
      redirect_to new_project_path, notice: 'Choose at least one category!'
    else
      puts cat_ids
      categories = Category.where(id: cat_ids)
      categories.each do |cat|
        @project.add_category(cat)
      end
      respond_to do |format|
        if @project.save
          params[:images]&.each do |image|
            Picture.create(image: image, project: @project)
          end
          format.html { redirect_to @project, notice: 'Project was successfully created.' }
          format.json { render :show, status: :created, location: @project }
        else
          format.html { render :new }
          format.json { render json: @project.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    cat_ids = project_params[:category_ids]&.map(&:to_i)
    if cat_ids.nil?
      redirect_to edit_project_path(@project), notice: 'Choose at least one category!'
    else
      puts cat_ids
      categories = Category.where(id: cat_ids)
      categories.each do |cat|
        @project.add_category(cat)
      end
      respond_to do |format|
        if @project.update(project_params)
          params[:images]&.each do |image|
            Picture.create(image: image, project: @project)
          end
          format.html { redirect_to @project, notice: 'Project was successfully updated.' }
          format.json { render :show, status: :ok, location: @project }
        else
          format.html { render :edit }
          format.json { render json: @project.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def savers
    @title = 'Savers'
    @project = Project.find(params[:id])
    @users = @project.savers
    # render 'show_save'
  end

  def save
    relation = current_user.save_project(@project)
    followers = @project.savers.count
    if relation
      unless @project.user.chat_id.nil?
        text = "#{current_user.fullname} bookmarked your project '#{@project.brief}'!\n"
        text += "Check his/her profile here: #{user_url(current_user)}"
        BOT.send_message(@project.user.chat_id, text)
      end
      # @user = current_user
      # @comments = @project.comments
      # @donated = @project.donations.map(&:amount).inject(0) { |sum, x| sum + x }
      # @user.save_project(@project)
      # redirect_to @project
      respond_to do |format|
        format.json do
          render json: {
            saved: {
              id: @project.id
            },
            saver: {
              id: relation.id
            },
            followers: {
              num: "#{followers} users".pluralize(followers)
            }
          }
        end
      end
    end
  end

  def search
    Project.reindex
    @projects = Project.search params[:search]
    @title = "#{@projects.count} " + 'result'.pluralize(@projects.count).upcase + " FOUND  FOR '#{params[:search].upcase}'"
    render 'index'
  end

  def forget
    @user = current_user
    @user.forget_project(@project)
    followers = @project.savers.count
    # redirect_to @project
    respond_to do |format|
      format.json do
        render json: {
          unfollowing: {
            id: @project.id
          },
          followers: {
            num: "#{followers} users".pluralize(followers)
          }
        }
      end
    end
  end

  def categories
    @title = 'Categories'
    @project = Project.find(params[:id])
    @categories = @project.categories
    # render 'show_follow'
  end

  def claim
    if @project.user_id == current_user.id && @project.funding_duration <= Date.today
      @project.finished = true
      @project.save
      current_user.increase_wallet(@project.donated)
    end
    redirect_to @project
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:project).permit(:brief, :description, :funding_duration, :funding_goal, images: [], category_ids: []).merge(user_id: current_user.id)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def following_project_button(project)
    return unless current_user
    following_relation = current_user.active_project_relationships.find_by(saved: project)
    if following_relation
      link_to 'Unfollow', forget_project_path(id: project, format: :json), method: 'delete', remote: true
    else
      link_to 'Follow', save_project_path(id: project, format: :json), method: 'post', remote: true
    end
  end
end

app/views/projects/_comment_form.html.erb
<%= form_for comment, remote: true, method: :post, url: comments_path do |f| %>

  <div class="field">
    <%= f.text_area :content, required: true, placeholder: "Type your message..." %>
  </div>

  <div class="field">
    <%= f.hidden_field :project_id, :value => project.id %>
  </div>

  <div class="comment-actions">
    <%= f.submit "Post", class: "create-btn btn-primary" %>
  </div>
<% end %>

app/views/projects/_comment_preview.html.erb
<li>
	<div class="comment-main">
		 <%#= link_to(gravatar_for(comment.user, 150, :class => "profile-pic"), comment.user, :class => "profile-pic")%>
		 <a href="<%= user_path(comment.user)%>"><%= image_tag comment.user.avatar.url(:comment), class: "img-circle"%></a>
		<div class="comment-square">
			<div class="comment-content">
				<span class="square-arrow"></span>
				<p class="comment-author">
					<%= link_to comment.user.fullname, comment.user%><span id="SPAN_21"></span>
				</p>
				<p class="comment-date">
					<%= distance_of_time_in_words(Time.now, comment.created_at)%> ago
				</p>
				<div class="spacer"></div>
				<p class=content-body>
						<span><%=comment.content%></span>
				</p>
			</div>
		</div>
	</div>
</li>

app/views/projects/_form.html.erb
<%= form_for project, html: { :multipart => true } do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
    <div class="field">
      <%= f.text_field :brief, required: true, placeholder: "Project Title" %>
    </div>
    <div class="field">
      <%= f.text_area :description, placeholder: "Description" %>
    </div>
    <div class="field">
      <%= f.number_field :funding_goal, min: '1', required: true,  placeholder: "Funding Goal"%>
    </div>
    <div class="group-field">
      <div class="category-field">
        <div class="field-title">
          Category
        </div>
        <div class="category-select">
          <%#= f.collection_check_boxes(:category_ids, Category.all, :id, :name,
          {:selected => @project.category_ids, :include_blank => false}, {:multiple => true}) %>
          <%index = 1%>
          <% Category.all.each do |cat| %>
            <div class= "category-option">
              <%= gen_input(index, cat, @categories).html_safe %>
              <%= gen_label(index, cat.name).html_safe %>
              <% index += 1%>
            </div>
          <% end %>
        </div>
      </div>
      <div class="date-field">
        <div class="field-title">
          Limit Date
        </div>
        <div class="date-select">
          <%= f.date_select :funding_duration, order: [:day, :month, :year], start_year: min_date.year, default: min_date, min: Date.today, required: true %>
        </div>
      </div>
    </div>
    <div class="picture-field">
      <%#= f.file_field "images[]", type: :file, multiple: true, accept: 'image/jpeg, image/jpg, image/gif, image/png' %>
      <%= f.fields_for :images do |builder| %>
        <%= file_field_tag "images[]", type: :file, multiple: true %>
      <% end %>
      <%#= f.file_field "images[]", type: :file, multiple: true %>
    </div>
    <div class="actions">
      <%= f.submit "Create Project", class: "create-btn" %>
    </div>
  <% end %>
</div>

app/views/projects/_form_edit.html.erb
<%= form_for project, html: { :multipart => true } do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row form-container">
    <div class="field">
      <%= f.text_field :brief, required: true, placeholder: "Project Title", :disabled => true %>
    </div>
    <div class="field">
      <%= f.text_area :description, placeholder: "Description" %>
    </div>
    <div class="group-field">
      <div class="category-field">
        <div class="field-title">
          Category
        </div>
        <div class="category-select">
          <%#= f.collection_check_boxes(:category_ids, Category.all, :id, :name,
          {:selected => @project.category_ids, :include_blank => false}, {:multiple => true}) %>
          <%index = 1%>
          <% Category.all.each do |cat| %>
            <div class= "category-option">
              <%= gen_input(index, cat, @categories).html_safe %>
              <%= gen_label(index, cat.name).html_safe %>
              <% index += 1%>
            </div>
          <% end %>
        </div>
      </div>
      <div class="date-field">
        <div class="field-title">
          Limit Date
        </div>
        <div class="date-select">
          <%= f.date_select :funding_duration, order: [:day, :month, :year], default: project.funding_duration, :disabled => true %>
        </div>
      </div>
    </div>
    <div class="picture-field">
      <%#= f.file_field "images[]", type: :file, multiple: true, accept: 'image/jpeg, image/jpg, image/gif, image/png' %>
      <%= f.fields_for :images do |builder| %>
        <%= file_field_tag "images[]", type: :file, multiple: true %>
      <% end %>
      <%#= f.file_field "images[]", type: :file, multiple: true %>
    </div>
    <div class="actions">
      <%= f.submit "Save Project", class: "create-btn" %>
      <div class="delete-btn">
        <%= link_to 'Delete Project', @project, method: :delete, data: { confirm: 'Are you sure?' }, class: "project-delete-btn" %>
      </div>
    </div>
  <% end %>
</div>

app/views/projects/_preview.html.erb
<div class='project-grid-item'>
  <h5 class='project-title'>
    <%= link_to truncate(project.brief, :length => 35, :separator => ' '), project%>
  </h5>
  <div class="meter-container">
  	<span class="meter nostripes">
      <%percentage = project.percentage%>
      <% if percentage > 100 %>
        <% max_width = 100 %>
      <% else %>
        <% max_width = percentage %>
      <% end %>
		  <span style="width: <%=max_width%>%"><span></span></span>
	  </span>
    <span class="meter-percentage"><%= percentage %>%</span>
  </div>
  <p class='project-author'>
    <%= link_to "By " + project.user.fullname, project.user%>
  </p>
  <% if defined? donated %>
    <p class='project-donation'>
      You have donated <%= number_to_currency(donated, :precision => 0) %>
      to this project.
    </p>
  <% end %>
  <p class='project-desc'>
    <%= truncate(project.description, :length => 230, :separator => ' ')  %>
  </p>
  <% if project.pictures.first.nil? %>
    <%= image_tag "/default/default_project_#{rand(0..3)}.jpg", class: "preview-img"%>
  <% else %>
    <%= image_tag project.pictures.first.image.url(:original), class: "preview-img"%>
  <% end %>
</div>

app/views/projects/edit.html.erb
<h1 class="title">Project Settings</h1>
<%= render 'form_edit', project: @project, min_date: @min_date %>

app/views/projects/index.html.erb
<% provide(:title, "#{@category} Projects") %>

<div class="title-elements">
  <div class="form">
    <span> Filter by category</span>
      <%= form_for(:category_filter, url: projects_path, method: :get) do |f| %>
      <span class="field">
        <% @options = Category.all.map { |a| [ a.name, a.id ] } %>
        <% @options.unshift(["All", 0]) %>
        <%= select_tag "category", options_for_select(@options, f.object || [@category, @default]), onchange: "this.form.submit();"%>
      </span>
      <% end %>
  </div>
  <h1 class="page-title"><%=@title%></h1>
  <div>
  </div>
</div>
<div class='project-grid-container'>
  <div class='project-grid'>
    <% @projects.each do |project|%>
    <%= render 'projects/preview', project: project %>
    <% end%>
  </div>
</div>

<%#= will_paginate @projects %>

<div class="digg_pagination">
    <%= paginate @projects %>
</div>

app/views/projects/index.js.erb
$(".project-grid").empty();
<% @projects.each do |pt| %>
  $(".project-grid").append("<%= escape_javascript(render partial: 'preview', locals: { project: pt }) %>");
<% end %>

$(".digg_pagination").empty();
$(".digg_pagination").append("<%= escape_javascript(paginate @projects) %>");

app/views/projects/new.html.erb
<% provide(:title, "New Project") %>

<h1 class="title">Start a new Project!</h1>
<%= render 'form', project: @project, min_date: @min_date %>

app/views/projects/show.html.erb
<% provide(:title, "Project: #{@project.brief}") %>

<section class="title-container">
  <div class="title-item title-owner">
    <a href="<%= user_path(@project.user) %>"><%= image_tag @project.user.avatar.url(:thumb), class: "img-circle"%></a>
    <div class="user">
      <span>By
        <%= link_to @project.user.fullname, @project.user %></span>
    </div>
  </div>
  <div class="title-item title-header">
    <div class="project-title">
      <h1 class="page-title">
        <%= @project.brief %>
      </h1>
    </div>
    <div class="project-desc">
      <h3>
        <%= @project.description %>
      </h3>
    </div>
  </div>
</section>

<section class="project-main">
  <div class="project-item project-image" id="content">
    <%#= image_tag @project.pictures.last.image.url(:original), class: "project-img"%>
    <div class="wrapper">
      <div class="slider-wrap">
        <div id="left" class="arrow pointer">L</div>
        <div id="right" class="arrow pointer a-right">R</div>
        <ul class="group"></ul>
        <% if @project.pictures.count.positive? %>
        <div class="slider group">
          <% @project.pictures.each do |picture| %>
          <div class="slide">
            <span class="centerer"></span>
            <%= image_tag picture.image.url(:original), class: "project-img"%>
          </div>
          <% end %>
        </div>
      <% else %>
        <div class="slider group">
          <% 4.times.each do |t| %>
          <div class="slide">
            <img src="<%= " /default/default_project_#{t}.jpg"%>" class="project-img"/>
          </div>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="project-item project-data">
    <div class="project-details">
      <li class="project-attr"><%= number_to_currency(@project.donated, :precision => 0) %></li>
      <li class="project-attr-desc">pledged of <%= number_to_currency(@project.funding_goal, :precision => 0) %> goal</li>
      <%if Date.today <= @project.funding_duration %>
        <li class="project-attr"><%= distance_of_time_in_words(Time.now, @project.funding_duration) %></li>
        <li class="project-attr-desc">to go</li>
      <%else%>
        <li class="project-attr"><%= "Status" %></li>
        <li class="project-attr-desc">Finished</li>
      <%end%>
      <li class="project-attr"><%= pluralize(@supporters, 'inverstor') %></li>
      <li class="project-attr-desc">supporting this project</li>
      <li id='followers-tag' class="project-attr"><%= pluralize(@followers, 'users') %></li>
      <li class="project-attr-desc">following this project</li>
      <%if !@project.categories.nil?%>
        <li class="project-attr">Related to</li>
        <li class="project-attr-desc category-links">
            <%= raw (@project.categories.map {|cat| link_to(cat.name, projects_path(:category => cat.id))}).to_a.join(", ")%>
        </li>
      <%end%>
    </div>
    <% if logged_in?%>
      <div class="project-buttons">
        <div id='boton' class='btn' value="<%= @default %>">
          <%= following_project_button(@project)%>
        </div>
        <div class="btn" value="Comment"><%= link_to "Comment", "#comments-section"%></div>
        <%if not @project.finished%>
          <div class="btn" value="Save"><%= link_to "Support Project", new_donation_path(:project_id => @project.id)%></div>
          <% if current_user == @project.user%>
            <%if Date.today >= @project.funding_duration %>
              <div class="btn" value="Claim"><%= link_to "Claim Project", {controller: "projects", action: "claim", id: @project.id}%></div>
            <% end %>
            <div class="btn" value="Edit"><%= link_to 'Settings', edit_project_path(@project) %></div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</section>

<section class="comments">
<h2 class="comments-title" id="comments-section">Comments</h2>
<% if logged_in?%>
<div class="comment-form">
  <%= render 'comment_form', {comment: @comment, project: @project}%>
</div>
<% end %>
<div class="comment-container">
  <% @comments.each do |comment| %>
  <div class="comment-item">
    <%= render 'comment_preview', {comment: comment, project: @project}%>
  </div>
  <% end %>
</div>
</section>